#!/usr/bin/env python
import rospy
from std_msgs.msg import String

node = rospy.init_node('rospy_tcpros_server')
pub = rospy.Publisher('/foo', String, queue_size=1)
(host, port) = rospy.impl.tcpros_base.get_tcpros_server_address()
print 'Started TCPROS server on port %d' % port

while not rospy.is_shutdown():
    pub.publish(String("hello"))
    rospy.sleep(1.0)


